### PR TITLE
Bundle update to dor-services 5.x (et al.)

### PR DESCRIPTION
**Pull request by atz**
Also ignore an extra log file that gets created.

### CODE REVIEW

**Comment by atz** [comment]
Odd, Travis passed for this same PR previously.

**Comment by mejackreed** [comment]
Seems like the issue might be with the `yard` gem? Curious why that is in there for the test group?

**Comment by atz** [comment]
Yeah, the Gemfile here was junk filled.  Found the yard thing.

**Comment by atz** [comment]
Not sure what the `rake doc` task is really accomplishing, since its output is:

```
Files:           0
Modules:         0 (    0 undocumented)
Classes:         0 (    0 undocumented)
Constants:       0 (    0 undocumented)
Methods:         0 (    0 undocumented)
 100.00% documented
```

:emoji_shrug:

**Comment by mejackreed** [comment]
Copy pasta?

**Comment by atz** [comment]
Yeah, referencing docs and directories that aren't in the project.

**Pull request merged**
